### ISSUE TITLE
Cleanup after implementation of "ephemeral ACRs"

### ISSUE THREAD

**Issue by mturczyn** [mturczyn/about-intrinsic#10]
- ~uncomment/clean .github/workflows/deploy-infra-and-website.yml~
- ~clean up GitHub Actions secrets~
- ~review Microsoft Entra ID~
- ~document old way of deploying docker image to webapp (initial pipeline generated by Azure .github/workflows/master_intrinsic-michal-turczyn.yml)~ (documented in readme section)

**Comment by mturczyn** [comment]
# Regarding last point

[In commit](https://github.com/mturczyn/about-intrinsic/blob/dcb988f0a15a63bf15e515d771265d1eb1e38b1c/.github/workflows/master_intrinsic-michal-turczyn.yml)
```
steps:
- name: Deploy to Azure Web App
  id: deploy-to-webapp
  uses: azure/webapps-deploy@v2
  with:
    app-name: 'intrinsic-michal-turczyn'
    slot-name: 'production'
    publish-profile: ${{ secrets.AzureAppService_PublishProfile_74f8e300dad240ab93104d5863e0758e }}
    images: 'intrinsicweb.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_b39ad9b085d94d62a5cac8feedfcc353 }}/about-intrinsic:${{ github.sha }}'
```

# Regarding Microsoft Entra Id
[In Azure Portal: Microsoft Entra ID -> App Regitrations](https://portal.azure.com/#view/Microsoft_AAD_IAM/ActiveDirectoryMenuBlade/~/RegisteredApps)
